- helm_deploy/hmpps-find-and-refer-an-intervention-service/values.yaml
Added dns host for ingress to resolve cert issue.
> Updated dns in ingress host

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
> move to shortened, compliant names

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/health/HealthPingCheck.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/health/HealthCheckTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/wiremock/HmppsAuthMockServer.kt
- src/test/resources/application-test.yml
Fix port clash and remove 'down' health integration test - can be added once we are calling out to external service
> No ticket/fix basic tests

- .circleci/config.yml
- Dockerfile
- docker-compose.yml
- helm_deploy/hmpps-find-and-refer-an-intervention-service/templates/_envs.tpl
- settings.gradle.kts
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/main/resources/db/local/init/init-db.sql
- src/main/resources/db/migration/V1_0__create_metadata_table.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/health/InfoTest.kt
- src/test/resources/application-integration.yml
- src/test/resources/application-test.yml
and env vars for pulling db secrets
> No ticket/local database setup

- settings.gradle.kts
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/health/InfoTest.kt
Update name to match reset of project.
> update gradle root project name

- helm_deploy/values-dev.yaml
- settings.gradle.kts
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/health/InfoTest.kt
Update dev env var to correct format
> No ticket/update root project name

- settings.gradle.kts
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/health/InfoTest.kt
revert project name change for testing.
> revert project name change

- Dockerfile
- settings.gradle.kts
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/health/InfoTest.kt
> No ticket/revert name change

- helm_deploy/hmpps-find-and-refer-an-intervention-service/values.yaml
Add env vars for db connection
> add db env vars

- .circleci/config.yml
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/IntegrationTestBase.kt
add circle db setup
update integration tests to run from their own config to avoid port clashes
> add circle db setup

- docker-compose.yml
- src/main/resources/application-local.yml
add local docker postgres config.
Add db connection values for local environment.
> add local docker postgres config

- .circleci/config.yml
- script/Dockerfile.data-dictionary
- script/build-data-dictionary.sh
Add schema spy generation task to mainline build config
> Fri 17/add schema doc generation

- .github/workflows/security_owasp.yml
- .github/workflows/security_trivy.yml
- .github/workflows/security_veracode_pipeline_scan.yml
- .github/workflows/security_veracode_policy_scan.yml
> move to environment variable SECURITY_ALERTS_SLACK_CHANNEL_ID

- .circleci/config.yml
- docker-compose-local.yml
- docker-compose.yml
- src/main/resources/application.yml
- src/test/resources/application-integration.yml
Migrate schema report to use hmpps generation library for schemaspy
Amend pipeline code accordingly and simplify
> Fri 17/db schema report

- .circleci/config.yml
Add build step to push to preprod, sequence after dev deploy and drop approval step
> Fri 95/add preprod build

- .circleci/config.yml
Add context specific to preprod env for this project
> Add context pointing to value in circle config for preprod

- README.md
- docker-compose-local.yml
- docker-compose.yml
- src/main/resources/application-local.yml
- src/main/resources/application.yml
Update hmpps-auth to start on port 9090 + update auth-url parameter to use docker container name rather than localhost for connecting from UI
> Update HMPPS Auth to use port 9090

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/authorization/UserTypeChecker.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/config/OpenApiConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/controller/HelloController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/service/ExampleApiService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/ResourceSecurityTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/wiremock/HmppsAuthMockServer.kt
Updates the HMPPS spring boot starter dependency to V7. 
The ktlint plugin has been updated as part of this and therefore some files have had to be reformatted as part of this pr
> Update hmpps spring boot to v7

- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/config/GlobalExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/controller/InterventionCatalogueController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jpa/repository/InterventionCatalogueFilterRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jpa/repository/InterventionCatalogueRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jpa/repository/InterventionCatalogueRepositoryImpl.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/service/InterventionCatalogueService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/controller/InterventionCatalogueControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/jpa/repository/InterventionCatalogueFilterRepositoryTest.kt
This PR implements the Intervention Type filter.
A user is able to pass an optional parameter for InterventionType to /interventions which will filter the results using the passed parameter.
> FRI-78: Implement InterventionType filter in interventionCatalogueController

- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/controller/InterventionCatalogueController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jpa/entity/CriminogenicNeed.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jpa/entity/RiskConsideration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jpa/repository/InterventionCatalogueFilterRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jpa/repository/InterventionCatalogueRepositoryImpl.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/service/InterventionCatalogueService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/controller/InterventionCatalogueControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/jpa/repository/InterventionCatalogueFilterRepositoryTest.kt
This PR implements setting and gender filters for the intervention catalogue
> FRI-78: Implement settingType and gender filters for intervention catalogue

- helm_deploy/values-prod.yaml
Add appropriate values to prevent deploy without pod creation
> Add config values applicable to prod to fix deployment

- .circleci/config.yml
- helm_deploy/values-prod.yaml
Another minor fix for helm deploy, applicable only to service
> Fri 96/prod values config

- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/controller/InterventionController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jpa/repository/InterventionFilterRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jpa/repository/InterventionRepositoryImpl.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/service/InterventionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/controller/InterventionControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/jpa/repository/InterventionFilterRepositoryTest.kt
Allow filtering of catalogue page results by programme name
> allow filtering by programme name

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/config/GlobalExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/controller/ServiceUserController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/dto/ServiceUserDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/service/ServiceUserService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/controller/ServiceUserControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/controller/ServiceUserControllerValidationTest.kt
initial service user end point that returns stub response
> initial service user end point that returns stub response

- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/dto/DeliveryLocationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/dto/InterventionDetailsDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/dto/NpsRegionDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/dto/PccRegionDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/dto/PduRefDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jpa/entity/DeliveryLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jpa/entity/NpsRegion.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jpa/entity/PccRegion.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jpa/entity/PduRef.kt
- src/main/resources/db/migration/V1_45__remove_delivery_location_null_constraints.sql
Get community locations from the delivery_location table
> Fri 470/delivery location table mapping

- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/dto/ServiceUserDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/service/ServiceUserService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/controller/ServiceUserControllerTest.kt
adding new field setting to be returned in the Service api endpoint
> adding setting to be returned in the Service api endpoint

- helm_deploy/hmpps-find-and-refer-an-intervention-service/templates/job-load-delivery-location.yaml
- helm_deploy/hmpps-find-and-refer-an-intervention-service/templates/job-load-intervention-catalogue-map.yaml
- helm_deploy/hmpps-find-and-refer-an-intervention-service/templates/job-load-intervention-catalogue-to-course-map.yaml
- helm_deploy/hmpps-find-and-refer-an-intervention-service/templates/job-load-interventions.yaml
- helm_deploy/hmpps-find-and-refer-an-intervention-service/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
fixing the service deployment issue
> fixing the service deployment issue

- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jobs/scheduled/loadinterventions/UpsertInterventionsJobConfiguration.kt
prevent the upsert intervention job to run on startup
> prevent the upsert intervention job to run on startup

- build.gradle.kts
- docker-compose.yml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/client/FindAndReferRestClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/client/RetryingClientCredentialsTokenResponseClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/config/WebClientConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/controller/ServiceUserController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/dto/ServiceUserDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/service/ServiceUserService.kt
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/controller/ServiceUserControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/controller/ServiceUserControllerValidationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/service/ServiceUserServiceTest.kt
- src/test/resources/application-integration.yml
- src/test/resources/application-test.yml
- wiremock_mappings/findAndReferAndMonitorDelius.json
integrating findAndReferDeliusApiClient to retrieve ServiceUser details
> integrating findAndReferDeliusApiClient to retrieve offender details

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jobs/scheduled/OnStartupJobLauncherFactory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jobs/scheduled/loadinterventions/UpsertInterventionsJobConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jobs/scheduled/loadmetadata/LoadDeliveryLocationJobConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jobs/scheduled/loadmetadata/LoadInterventionCatalogueMapJobConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jobs/scheduled/loadmetadata/LoadInterventionCatalogueToCourseMapJobConfiguration.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/loadmetadata/DeliveryLocationReaderTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/loadmetadata/DeliveryLocationWriterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/loadmetadata/InterventionCatalogueMapReaderTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/loadmetadata/InterventionCatalogueMapWriterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/loadmetadata/InterventionCatalogueToCourseMapWriterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/loadmetadata/InterventionCatalogueToCourserMapReaderTest.kt
> fixing the deployment issue

- src/main/resources/application.yml
renaming the clientId for find and refer external api client call
> renaming the clientId for find and refer external api client call

- src/main/resources/application.yml
> configure the scopes

- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/config/GlobalExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/controller/ServiceUserController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/integration/controller/ServiceUserControllerTest.kt
handling external service exception
> handling external service exception

- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/service/ServiceUserServiceTest.kt
- wiremock_mappings/findAndReferAndMonitorDelius.json
The url configured for limited access offender check needs to be changed.
> correct the url for limited access offender check

- helm_deploy/hmpps-find-and-refer-an-intervention-service/values.yaml
we need configure sentry auth token for the application to successfully connect to sentry and push the information
> setting the sentry auth token variable

- .github/workflows/branch-name-validator.yml
- README.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jpa/entity/Referral.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/findandreferanintervention/jpa/repository/ReferralRepository.kt
- src/main/resources/db/migration/V1_50__create_referral_table.sql
This PR creates a referral table so we have somewhere to store a minimal amount of information about an event before processing and sending it on to the Manage and Deliver service.
> APG-968: Create referral table

- build.gradle.kts
changing the sentry library io.sentry:sentry-spring-boot-starter-jakarta
> fix the sentry config issue
